# Generated by Django 3.2.3 on 2021-07-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='CMRGCs', max_length=8, unique=True),
        ),
    ]
