# Generated by Django 3.2.3 on 2021-08-05 09:26

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api.models.room_code_generator, max_length=8, unique=True),
        ),
    ]
